# Start with a Python base image
FROM python:3.9

# Set the PYTHONPATH to include the current working directory
ENV PYTHONPATH="/core-management"

# Set the working directory
WORKDIR /core-management

# Copy the core-management
COPY . /core-management

# Copy the proto file
COPY proto/core_management.proto ./

# Install gRPC tools
RUN pip install pytest==6.2.5 unittest2 mock grpcio grpcio-tools grpcio-testing

# Generate the gRPC files directly into /core-management
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. core_management.proto

# Copy the server and client directories
COPY server/ ./server/
COPY client/ ./client/

# Open port
EXPOSE 1500

# To start server and client
CMD ["sh", "-c", "python server/server.py & sleep 2; python client/client.py"]

# To run tests
#ENV PYTHONPATH="/core-management/server"
#CMD ["pytest", "tests", "--disable-warnings", "-v"]

